### PR TITLE
Added depth argument to lsp-treemacs--expand

### PR DESCRIPTION
**Pull request by ericdallo**
https://github.com/emacs-lsp/lsp-treemacs/pull/42

### CODE REVIEW

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-treemacs/pull/41

**Comment by yyoncho** [comment]
Can you rebase?

**Comment by ericdallo** [comment]
Done @yyoncho, I'm kind of lost of what is missing for this feature works :sweat_smile:

**Comment by yyoncho** [comment]
I think that now we are good and we can use in dap-mode.

**Pull request merged**
