### PR TITLE
CI Implementation

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by jcs090218** [comment]
All check have passed, See https://github.com/jcs-PR/lsp-treemacs/actions/runs/522849071.

Not sure if we either have to merge this to active GitHub Actions or this feature is disable by default in this repository.

**Comment by jcs090218** [comment]
Okay, I am getting these warnings after enabled `byte-compile-error-on-warn`.

```
In toplevel form:
lsp-treemacs.el:1211:1: Warning: Unused lexical variable `start'
lsp-treemacs.el:1211:1: Warning: Unused lexical variable `uri'
lsp-treemacs.el:1211:1: Warning: Unused lexical variable `detail\?'
lsp-treemacs.el:1211:1: Warning: Unused lexical variable `name'
```

Any idea?

**Comment by yyoncho** [comment]
> Okay, I am getting these warnings after enabled `byte-compile-error-on-warn`.
> 
> ```
> In toplevel form:
> lsp-treemacs.el:1211:1: Warning: Unused lexical variable `start'
> lsp-treemacs.el:1211:1: Warning: Unused lexical variable `uri'
> lsp-treemacs.el:1211:1: Warning: Unused lexical variable `detail\?'
> lsp-treemacs.el:1211:1: Warning: Unused lexical variable `name'
> ```
> 
> Any idea?

Most likely these variables must be fixed.

**Comment by jcs090218** [comment]
> Most likely these variables must be fixed.

Yeah, I am not very familiar with the code here. Do you know how to fix these warnings?

**Comment by jcs090218** [comment]
Fixed by this commit, https://github.com/emacs-lsp/lsp-treemacs/pull/97/commits/4010ac36e3da3bcaa2d997e1f7095b6827e64f3b.

All CI have passed! 🎉 See https://github.com/jcs-PR/lsp-treemacs/actions/runs/523185742.

**Comment by yyoncho** [comment]
Can you resolve the conflicts?

**Comment by jcs090218** [comment]
Resolved!

**Comment by yyoncho** [comment]
> Resolved!

Thank you, sorry for causing the merge conflict, I forgot about this PR.

**Pull request merged**
